---
# tasks file for nar_mellanox_hci
#- name: Primary setup on Mellanox switches
#  include_tasks: primary_setup.yaml

# Configure Spanning tree settings on the edge ports
- name: Configure spanning tree settings on edge ports
  include_tasks: spanning_tree.yaml
  
# Configure IPL MLAG  
#- name: Create Inter Peer link(IPL) MLAG between ONYX switches
#  include_tasks: ipl_mlag.yaml

# Configure Storage MLAG ports
#- name: Create storage MLAG between ONYX switches
#  include_tasks: storage_mlag.yaml
 
# Configure Compute  ports
#- name: Configure the compute ports
#  include_tasks: compute_config.yaml
  
