#Set MTU for Port Channel
- name: Set Jumbo frames for port channels
  onyx_config:
    lines:
    - interface mlag-port-channel {{item.mlag_id}} mtu 9216
    - interface mlag-port-channel {{item.mlag_id}} no shutdown
  with_items:
  -  "{{storage_interfaces}}"

# Create Link aggregation for Storage Links
- name: Create link aggregation for storage ports
  onyx_linkagg:
    name: Mpo{{item.mlag_id}}
    members: "{{item.members}}"
    mode: active
  with_items:
  -  "{{storage_interfaces}}"
  tags:
  -  storage_mlag

# Set vlans for the storage ports
- name: Set vlans for the storage ports
  onyx_l2_interface:
    name: Po{{item[1].mlag_id}}
    mode: hybrid
    access_vlan: 2
    trunk_allowed_vlans: "{{item[0].vlan_id}}"
  with_nested:
  -  "{{netapp_hci_vlans}}"
  -  "{{storage_interfaces}}"
  when: item[0].vlan_name == "iSCSI_Storage"


